/* WARNING: This header contains code generated by ./gen-fan-detect-defs.py */
/* !!! DO NOT EDIT THIS FILE BY HAND !!! */
#pragma once

#include <map>
#include <set>

static const std::map<std::string, std::set<phosphor::fan::Properties>>
fanDetectMap = {
    {"tach",{
        {"system/chassis/fan0","Chassis location A1",{"blower1", "blower2"}},
        {"system/chassis/fan1","Chassis location A2",{"blower3", "blower4"}},
        {"system/chassis/fan2","Chassis location A3",{"blower5", "blower6"}},
        {"system/chassis/fan3","Chassis location A4",{"blower7", "blower8"}},
    }},
    {"gpio",{
        {"system/chassis/fan4","Chassis location A5",{"pin_4"}},
        {"system/chassis/fan5","Chassis location A6",{"pin_5"}},
    }},
};
