/* WARNING: This header contains code generated by ./gen-fan-detect-defs.py */
/* !!! DO NOT EDIT THIS FILE BY HAND !!! */
#pragma once

#include <map>
#include <set>

static const std::map<std::string, std::set<phosphor::fan::Properties>>
fanDetectMap = {
    {"tach",{
        {"/system/chassis/fan0","Chassis location A1",{"fan0"}},
        {"/system/chassis/fan1","Chassis location A2",{"fan1"}},
        {"/system/chassis/fan2","Chassis location A3",{"fan2"}},
        {"/system/chassis/fan3","Chassis location A4",{"fan3"}},
    }},
    {"gpio",{
        {"/system/chassis/fan4","Chassis location A5",{"pin_4"}},
        {"/system/chassis/fan5","Chassis location A6",{"pin_5"}},
    }},
};
