#!/usr/bin/env python

"""
This script parses the given fan presence definition yaml file and generates
header file(s) based on the defined methods for determining when a fan is
present.
"""

import os
import sys
import yaml
from argparse import ArgumentParser


def create_detection_header(detection_type):
    """
    Creates the header file based on the presence detection value given within
    the yaml file. The associated fan presence detection application includes
    this header.

    Parameter descriptions:
    detection_type      The defined type of fan presence detection
    """
    src_dir = os.path.dirname(os.path.abspath(__file__))
    detection_type = detection_type.replace(" ", "-")
    head_file = os.path.join(src_dir, detection_type)
    head_file = head_file + ".hpp"
    if not os.path.isfile(head_file):
        with open(head_file, 'w') as ofile:
            ofile.write("/* WARNING: This header contains code generated ")
            ofile.write("by " + __file__ + " */\n")
            ofile.write("/* !!! DO NOT EDIT THIS FILE BY HAND !!! */\n\n")
            ofile.write("static const std::map<std::string, ")
            ofile.write("std::map<std::string, ")
            ofile.write("std::string>>\nfanDetectionMap = {\n")

    return head_file


def add_fan(head_file, fan_info):
    """
    Adds each fan's yaml entry presence detection information to the
    corresponding header file for the defined detection method

    Parameter descriptions:
    head_file           Header file to add fan information to
    fan_info            Fan presence detection information
    """
    with open(head_file, 'a') as ofile:
        pres_dict = fan_info['Presence']
        for pres_rotors in fan_info['Presence']:
            ofile.write("    {\"" + pres_rotors['Rotor'] + "\",{\n")
            inv_path = os.path.join(fan_info['Inventory'], "")
            ofile.write("        {\"inventory\",\"" +
                        inv_path + fan_info['Fan'] + "\"},\n")
            ofile.write("        {\"description\",\"" +
                        fan_info['Description'] + "\"},\n")
            ofile.write("    }},\n")


def parse_yaml(yaml_file):
    """
    Parse the given yaml file, creating a header file for each 'Detection'
    types found to be included within the app supporting presence detection
    by that type.

    Parameter descriptions:
    yaml_file           File to be parsed for fan presences definitions
    """
    head_list = []
    with open(yaml_file, 'r') as input_file:
        head_file = ""
        yaml_input = yaml.safe_load(input_file)
        for fan in yaml_input:
            head_file = create_detection_header(fan['Detection'])
            add_fan(head_file, fan)
            head_list += [head_file]
    for header in head_list:
        with open(head_file, 'a') as ofile:
            ofile.write("};\n")


if __name__ == '__main__':
    parser = ArgumentParser()
    # Input yaml containing how each fan's presence detection should be done
    parser.add_argument("-y", "--yaml", dest="pres_yaml",
                        default=
                        "example/fan-detect.yaml",
                        help=
                        "Input fan presences definition yaml file to parse")
    args = parser.parse_args(sys.argv[1:])

    # Verify given yaml file exists
    yaml_file = os.path.abspath(args.pres_yaml)
    if not os.path.isfile(yaml_file):
        print "Unable to find input yaml file " + yaml_file
        exit(1)

    parse_yaml(yaml_file)
