/* WARNING: This header contains code generated by ./gen-fan-detect-defs.py */
/* !!! DO NOT EDIT THIS FILE BY HAND !!! */

static const std::map<std::string, std::map<std::string, std::string>>
fanDetectionMap = {
    {"blower1",{
        {"inventory","system/chassis/fan0"},
        {"description","Chassis location A1"},
    }},
    {"blower2",{
        {"inventory","system/chassis/fan0"},
        {"description","Chassis location A1"},
    }},
    {"blower3",{
        {"inventory","system/chassis/fan1"},
        {"description","Chassis location A2"},
    }},
    {"blower4",{
        {"inventory","system/chassis/fan1"},
        {"description","Chassis location A2"},
    }},
    {"blower5",{
        {"inventory","system/chassis/fan2"},
        {"description","Chassis location A3"},
    }},
    {"blower6",{
        {"inventory","system/chassis/fan2"},
        {"description","Chassis location A3"},
    }},
    {"blower7",{
        {"inventory","system/chassis/fan3"},
        {"description","Chassis location A4"},
    }},
    {"blower8",{
        {"inventory","system/chassis/fan3"},
        {"description","Chassis location A4"},
    }},
};
